// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD-3jZJeX9EbPWkTRUT_KiISiSH11wIGM',
    appId: '1:864866976826:web:dd449c0b0ae8d2e1e3e103',
    messagingSenderId: '864866976826',
    projectId: 'roulette-prizes-app-15fff',
    authDomain: 'roulette-prizes-app-15fff.firebaseapp.com',
    storageBucket: 'roulette-prizes-app-15fff.appspot.com',
    measurementId: 'G-ZRY6CYTTNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCowpB0VGYdlBAccuuaV2N70DcdSedxb54',
    appId: '1:864866976826:android:7306a95aea961ed5e3e103',
    messagingSenderId: '864866976826',
    projectId: 'roulette-prizes-app-15fff',
    storageBucket: 'roulette-prizes-app-15fff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeqMa53orWkU5h-c4mF4R3J8r5q_i7cs4',
    appId: '1:864866976826:ios:45980bc687dd8f53e3e103',
    messagingSenderId: '864866976826',
    projectId: 'roulette-prizes-app-15fff',
    storageBucket: 'roulette-prizes-app-15fff.appspot.com',
    iosBundleId: 'com.example.roulettePrizesApp',
  );
}
